/* eslint-disable no-unused-vars */
export const LOGO_URL =
  "https://e7.pngegg.com/pngimages/427/304/png-clipart-pizza-sticker-cartoon-drawing-pizza-food-fruit-thumbnail.png";

export let items = [
  {
    id: 1,
    name: "Heavy Heaven",
    image: "https://www.peppes.no/bilder_webshop/0130.jpg",
    ingredients:
      "Pepperoni, garlic-spiced meatballs, marinated beef, red onion and oregano.",
    allergens: "Wheat, Gluten, Milk",
    regularPrice: 100,
    largePrice: 310,
    vegetarian: false,
    glutenFree: false,
  },
  {
    id: 2,
    name: "Chicken Flyaway",
    image: "https://www.peppes.no/bilder_webshop/0119.jpg",
    ingredients: "Marinated chicken, corn, leek and red pepper.",
    allergens: "Wheat, Gluten, Milk",
    regularPrice: 110,
    largePrice: 298,
    vegetarian: false,
    glutenFree: false,
  },
  {
    id: 3,
    name: "Oh My Garden!",
    image: "https://www.peppes.no/bilder_webshop/0141.jpg",
    ingredients:
      "Avocado, red onion, marinated aromatic mushrooms, olives, cherry tomatoes and kale mix. The cheese has been replaced with a tasty vegan aioli. Topped with freshly ground pepper and lime zest.",
    allergens: "Wheat, Gluten, Milk",
    regularPrice: 115,
    largePrice: 310,
    vegetarian: true,
    glutenFree: false,
  },
  {
    id: 4,
    name: "Green Garden",
    image: "https://www.peppes.no/bilder_webshop/0147.jpg",
    ingredients:
      "Avocado, red onion, marinated aromatic mushrooms, olives, cherry tomatoes, kale mix, fresh mozzarella and Peppe's cheese mixture. Topped with freshly ground pepper and lime zest.",
    allergens: "Wheat, Gluten, Milk",
    regularPrice: 110,
    largePrice: 310,
    vegetarian: true,
    glutenFree: false,
  },
  {
    id: 5,
    name: "GLUTEN-FREE Chicken Flyaway",
    image: "https://www.peppes.no/bilder_webshop/0319.jpg",
    ingredients: "Marinated chicken, corn, leek and red pepper.",
    allergens: "Soya, Milk",
    regularPrice: 115,
    largePrice: 350,
    vegetarian: false,
    glutenFree: true,
  },

  {
    id: 6,
    name: "Pepperoni",
    image: "https://www.peppes.no/bilder_webshop/0191.jpg",
    ingredients: "Pepperoni and oregano.",
    allergens: "Wheat, Gluten, Milk",
    regularPrice: 148,
    largePrice: 300,
    vegetarian: false,
    glutenFree: false,
  },
  {
    id: 7,
    name: "American Make Your Own",
    image: "https://www.peppes.no/bilder_webshop/0107.jpg",
    ingredients:
      "Avocado, red onion, marinated aromatic mushrooms, olives, cherry tomatoes and cheese are in place!",
    allergens: "Wheat, Gluten, Milk",
    regularPrice: 125,
    largePrice: 360,
    vegetarian: true,
    glutenFree: false,
  },
  {
    id: 8,
    name: "GLUTEN FREE Oh My Garden!",
    image: "https://www.peppes.no/bilder_webshop/0341.jpg",
    ingredients:
      "Avocado, red onion, marinated aromatic mushrooms, olives, cherry tomatoes and kale mix. The cheese has been replaced with a tasty vegan aioli. Topped with freshly ground pepper and lime zest.",
    allergens: "Soya, Mustard",
    regularPrice: 160,
    largePrice: 340,
    vegetarian: true,
    glutenFree: true,
  },
  {
    id: 9,
    name: "GLUTEN-FREE Big Shot",
    image: "https://www.peppes.no/bilder_webshop/0336.jpg",
    ingredients: "Marinated chicken, bacon, pepperoni, tomato and oregano.",
    allergens: "Soya, Milk",
    regularPrice: 160,
    largePrice: 340,
    vegetarian: false,
    glutenFree: true,
  },
];

// let pizzaItems1 = [
//   {
//     id: 1,
//     name: "Heavy Heaven",
//     image: "https://www.peppes.no/bilder_webshop/0130.jpg",
//     ingredients:
//       "Pepperoni, garlic-spiced meatballs, marinated beef, red onion and oregano.",
//     allergens: "Wheat, Gluten, Milk",
//     regularPrice: 100,
//     largePrice: 310,
//     vegetarian: false,
//     glutenFree: false,
//   },
//   {
//     id: 2,
//     name: "Chicken Flyaway",
//     image: "https://www.peppes.no/bilder_webshop/0119.jpg",
//     ingredients: "Marinated chicken, corn, leek and red pepper.",
//     allergens: "Wheat, Gluten, Milk",
//     regularPrice: 110,
//     largePrice: 298,
//     vegetarian: false,
//     glutenFree: false,
//   },
//   {
//     id: 3,
//     name: "Oh My Garden!",
//     image: "https://www.peppes.no/bilder_webshop/0141.jpg",
//     ingredients:
//       "Avocado, red onion, marinated aromatic mushrooms, olives, cherry tomatoes and kale mix. The cheese has been replaced with a tasty vegan aioli. Topped with freshly ground pepper and lime zest.",
//     allergens: "Wheat, Gluten, Milk",
//     regularPrice: 115,
//     largePrice: 310,
//     vegetarian: true,
//     glutenFree: false,
//   },
//   {
//     id: 4,
//     name: "Green Garden",
//     image: "https://www.peppes.no/bilder_webshop/0147.jpg",
//     ingredients:
//       "Avocado, red onion, marinated aromatic mushrooms, olives, cherry tomatoes, kale mix, fresh mozzarella and Peppe's cheese mixture. Topped with freshly ground pepper and lime zest.",
//     allergens: "Wheat, Gluten, Milk",
//     regularPrice: 110,
//     largePrice: 310,
//     vegetarian: true,
//     glutenFree: false,
//   },
//   {
//     id: 5,
//     name: "GLUTEN-FREE Chicken Flyaway",
//     image: "https://www.peppes.no/bilder_webshop/0319.jpg",
//     ingredients: "Marinated chicken, corn, leek and red pepper.",
//     allergens: "Soya, Milk",
//     regularPrice: 115,
//     largePrice: 350,
//     vegetarian: false,
//     glutenFree: true,
//   },
//   {
//     id: 6,
//     name: "Thai Chicken",
//     image: "https://www.peppes.no/bilder_webshop/0115.jpg",
//     ingredients:
//       "Satay chicken, paprika, red onion, pineapple, satay sauce and peanuts. Top with fresh coriander and lime zest.",
//     allergens: "Wheat, Gluten, Soya, Milk, Peanuts",
//     regularPrice: 115,
//     largePrice: 328,
//     vegetarian: false,
//     glutenFree: false,
//   },
//   {
//     id: 7,
//     name: "Pepper Steak",
//     image: "https://www.peppes.no/bilder_webshop/0111.jpg",
//     ingredients: "Marinated beef, paprika and oregano.",
//     allergens: "Wheat, Gluten, Milk",
//     regularPrice: 120,
//     largePrice: 300,
//     vegetarian: false,
//     glutenFree: false,
//   },
//   {
//     id: 8,
//     name: "Big Shot",
//     image: "https://www.peppes.no/bilder_webshop/0136.jpg",
//     ingredients: "Marinated chicken, bacon, pepperoni, tomato and oregano.",
//     allergens: "Wheat, Gluten, Soya, Milk",
//     regularPrice: 125,
//     largePrice: 350,
//     vegetarian: false,
//     glutenFree: false,
//   },
//   {
//     id: 9,
//     name: "Pepperoni",
//     image: "https://www.peppes.no/bilder_webshop/0191.jpg",
//     ingredients: "Pepperoni and oregano.",
//     allergens: "Wheat, Gluten, Milk",
//     regularPrice: 148,
//     largePrice: 300,
//     vegetarian: false,
//     glutenFree: false,
//   },
//   {
//     id: 10,
//     name: "The Tropical",
//     image: "https://www.peppes.no/bilder_webshop/0102.jpg",
//     ingredients: "Pepperoni, pineapple and oregano.",
//     allergens: "Wheat, Gluten, Milk",
//     regularPrice: 125,
//     largePrice: 290,
//     vegetarian: false,
//     glutenFree: false,
//   },
//   {
//     id: 11,
//     name: "American Make Your Own",
//     image: "https://www.peppes.no/bilder_webshop/0107.jpg",
//     ingredients:
//       "Avocado, red onion, marinated aromatic mushrooms, olives, cherry tomatoes and cheese are in place!",
//     allergens: "Wheat, Gluten, Milk",
//     regularPrice: 125,
//     largePrice: 360,
//     vegetarian: true,
//     glutenFree: false,
//   },
//   {
//     id: 12,
//     name: "GLUTEN FREE Oh My Garden!",
//     image: "https://www.peppes.no/bilder_webshop/0341.jpg",
//     ingredients:
//       "Avocado, red onion, marinated aromatic mushrooms, olives, cherry tomatoes and kale mix. The cheese has been replaced with a tasty vegan aioli. Topped with freshly ground pepper and lime zest.",
//     allergens: "Soya, Mustard",
//     regularPrice: 160,
//     largePrice: 340,
//     vegetarian: true,
//     glutenFree: true,
//   },
//   {
//     id: 13,
//     name: "GLUTEN-FREE Pepper Steak",
//     image: "https://www.peppes.no/bilder_webshop/0311.jpg",
//     ingredients: "Marinated beef, paprika and oregano.",
//     allergens: "Soya, Milk",
//     regularPrice: 160,
//     largePrice: 350,
//     vegetarian: false,
//     glutenFree: true,
//   },
//   {
//     id: 14,
//     name: "GLUTEN-FREE Big Shot",
//     image: "https://www.peppes.no/bilder_webshop/0336.jpg",
//     ingredients: "Marinated chicken, bacon, pepperoni, tomato and oregano.",
//     allergens: "Soya, Milk",
//     regularPrice: 160,
//     largePrice: 340,
//     vegetarian: true,
//     glutenFree: true,
//   },
// ];

// let jsonData = {[
//   {
//       "id": 1,
//       "name": "Heavy Heaven",
//       "image": "https://www.peppes.no/bilder_webshop/0130.jpg",
//       "ingredients": "Pepperoni, garlic-spiced meatballs, marinated beef, red onion and oregano.",
//       "allergens": "Wheat, Gluten, Milk",
//       "regularPrice": 100.00,
//       "largePrice": 310.00,
//       "vegetarian": false,
//       "glutenFree": false
//   },
//   {
//       "id": 2,
//       "name": "Chicken Flyaway",
//       "image": "https://www.peppes.no/bilder_webshop/0119.jpg",
//       "ingredients": "Marinated chicken, corn, leek and red pepper.",
//       "allergens": "Wheat, Gluten, Milk",
//       "regularPrice": 110.00,
//       "largePrice": 298.00,
//       "vegetarian": false,
//       "glutenFree": false
//   },
//   {
//       "id": 3,
//       "name": "Oh My Garden!",
//       "image": "https://www.peppes.no/bilder_webshop/0141.jpg",
//       "ingredients": "Avocado, red onion, marinated aromatic mushrooms, olives, cherry tomatoes and kale mix. The cheese has been replaced with a tasty vegan aioli. Topped with freshly ground pepper and lime zest.",
//       "allergens": "Wheat, Gluten, Milk",
//       "regularPrice": 115.00,
//       "largePrice": 310.00,
//       "vegetarian": true,
//       "glutenFree": false
//   },
//   {
//       "id": 4,
//       "name": "Green Garden",
//       "image": "https://www.peppes.no/bilder_webshop/0147.jpg",
//       "ingredients": "Avocado, red onion, marinated aromatic mushrooms, olives, cherry tomatoes, kale mix, fresh mozzarella and Peppe's cheese mixture. Topped with freshly ground pepper and lime zest.",
//       "allergens": "Wheat, Gluten, Milk",
//       "regularPrice": 110.00,
//       "largePrice": 310.00,
//       "vegetarian": true,
//       "glutenFree": false
//   },
//   {
//       "id": 5,
//       "name": "GLUTEN-FREE Chicken Flyaway",
//       "image": "https://www.peppes.no/bilder_webshop/0319.jpg",
//       "ingredients": "Marinated chicken, corn, leek and red pepper.",
//       "allergens": "Soya, Milk",
//       "regularPrice": 115.00,
//       "largePrice": 350.00,
//       "vegetarian": false,
//       "glutenFree": true
//   },
//   {
//       "id": 6,
//       "name": "Pepperoni",
//       "image": "https://www.peppes.no/bilder_webshop/0191.jpg",
//       "ingredients": "Pepperoni and oregano.",
//       "allergens": "Wheat, Gluten, Milk",
//       "regularPrice": 148.00,
//       "largePrice": 300.00,
//       "vegetarian": false,
//       "glutenFree": false
//   },
//   {
//       "id": 7,
//       "name": "American Make Your Own",
//       "image": "https://www.peppes.no/bilder_webshop/0107.jpg",
//       "ingredients": "Avocado, red onion, marinated aromatic mushrooms, olives, cherry tomatoes and cheese are in place!",
//       "allergens": "Wheat, Gluten, Milk",
//       "regularPrice": 125.00,
//       "largePrice": 360.00,
//       "vegetarian": true,
//       "glutenFree": false
//   },
//   {
//       "id": 8,
//       "name": "GLUTEN FREE Oh My Garden!",
//       "image": "https://www.peppes.no/bilder_webshop/0341.jpg",
//       "ingredients": "Avocado, red onion, marinated aromatic mushrooms, olives, cherry tomatoes and kale mix. The cheese has been replaced with a tasty vegan aioli. Topped with freshly ground pepper and lime zest.",
//       "allergens": "Soya, Mustard",
//       "regularPrice": 160.00,
//       "largePrice": 340.00,
//       "vegetarian": true,
//       "glutenFree": true
//   },
//   {
//       "id": 9,
//       "name": "GLUTEN-FREE Big Shot",
//       "image": "https://www.peppes.no/bilder_webshop/0336.jpg",
//       "ingredients": "Marinated chicken, bacon, pepperoni, tomato and oregano.",
//       "allergens": "Soya, Milk",
//       "regularPrice": 160.00,
//       "largePrice": 340.00,
//       "vegetarian": true,
//       "glutenFree": true
//   }
// ]};

export let userLogin = {
  name: null,
  id: null,
  login: false,
};
